-- 1 - DECLARE VARIABLES
DECLARE @TAG_ID NUMERIC

-- 2 - DECLARE CURSOR
DECLARE C_1 CURSOR FOR 
	SELECT TOP 5 A.TAG_ID FROM ALARM_LIST A
	RIGHT JOIN AV_LIST B ON A.TAG_ID = B.AV_TAG_ID
	WHERE B.AV_DESC IS NULL
	  AND A.ALM_DATE IS NOT NULL
	  
-- OPEN THE CURSOR  
OPEN C_1
	FETCH NEXT FROM C_1 INTO @TAG_ID

-- SET THE STATUS FOR THE CURSOR	
WHILE @@FETCH_STATUS = 0
BEGIN
-- 4 - BEGIN THE CUSTOM BUSINESS LOGIC
	SELECT SP_NO, 
			 AV_TAG_ID, 
			 AV_TAG_NAME, 
			 (SELECT ALM_DESC FROM ALARM_LIST WHERE TAG_ID = @TAG_ID) AS AV_DESC 
		FROM AV_LIST
		WHERE AV_TAG_ID = @TAG_ID
	
	-- 5 - FETCH THE NEXT RECORD FROM THE CURSOR
	FETCH NEXT FROM C_1 INTO @TAG_ID
END
-- 6 - CLOSE THE CURSOR
CLOSE C_1

-- 7 - DEALLOCATE THE CURSOR
DEALLOCATE C_1
